spring:
  http:
    message:
      converters:
        preferred-json-mapper: jackson

  profiles:
    include: oauth

  datasource:
    #        url: jdbc:sqlite:db.sqlite
    #        driver-class-name: org.sqlite.JDBC
    #        username: ${SQLite_Username}
    #        password: ${SQLite_Password}
    url: jdbc:mysql://localhost:3306/db2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MySQL_Username}
    password: ${MySQL_Password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: true


  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  token:
    access-token-valid-time: ${access-token-valid-time}
    refresh-token-valid-time: ${refresh-token-valid-time}

iamport:
  key: 1231234
  secret: 6545323