spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
    #    url: jdbc:mysql://${RDS_URL}/todo
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: admin
    #    password: angksehwjs031

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: true


  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdidsfdsfdfsdfsdfsdfsdfsd

iamport:
  key: 1231234
  secret: 6545323